name: push-version
description: Tag the repository with the new version
author: Dan Drew

runs:
  using: composite
  steps:
    - name: Push tag
      shell: bash
      run: |
        # Push tags
        readonly new_tag=v${{ env.next_version }}

        if [[ "${new_tag}" == 'v' ]]; then
          echo 'No new version found'
          exit 1
        fi

        git tag ${new_tag}
        git push origin ${new_tag}
